defaults:
  - _self_
  - env: dflex_ant
  - alg: shac

general:
  train: True
  logdir: logs
  render: False
  device: cuda:0
  run_wandb: False
  seed: 42
  checkpoint:
  checkpoint_with_buffer: False
  eval_runs: 12
  pretrain: 
  pretrain_steps: 50000

wandb:
  project: TODO
  entity: TODO
  group: 
