defaults:
  - _self_
  - env: dflex_ant
  - alg: shac

general:
  train: True
  logdir: logs
  render: False
  device: cuda:0
  run_wandb: False
  seed: 42
  checkpoint:
  eval_runs: 12

wandb:
  project:
  entity:
  group: 
