defaults:
  - _self_
  - env: dflex_ant
  - alg: shac

general:
  train: True
  logdir: logs
  render: False
  device: cuda:0
  run_wandb: False
  seed: 42
  checkpoint:
  checkpoint_with_buffer: False
  eval_runs: 5
  pretrain: 
  # pretrain: /storage/home/hcoda1/7/igeorgiev3/git/FoWM/data/dflex-hopper/ep_data_HopperEnv_ep131072_1.pt
  # pretrain: /storage/home/hcoda1/7/igeorgiev3/git/FoWM/data/dflex-cartpole/ep_data_CartPoleSwingUpEnv_ep67584_1.pt
  pretrain_steps: 50000
  multitask: True

wandb:
  project: fowm
  entity: pair-diffusion
  group: 

obs: state
task: reacher-easy
seed: ${general.seed}
tasks: ???
multitask: True
work_dir: ???
task_title: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
epochs: 10_000
eval_freq: 1000
horizon: 3
data_dir: /storage/coda1/p-agarg35/0/shared/tdmpc2-datasets/mt80

buffer:
  _target_: forl.utils.buffer.Buffer
  buffer_size: ???
  batch_size: 64
  horizon: ${horizon}
  device: ${general.device}
