name: fowm-s4
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - pandas
  - matplotlib
  - seaborn
  - notebook
  - pip
  - pip:
      - tensordict
      - torchrl
      - hydra-submitit-launcher
      - wandb
      - black
      - termcolor
      - tqdm
      - tensorboardX
      - rl_games # used as a baseline for comparison. Not required!
      # dflex simulator is used for examples. It is not required for the library.
      - git+https://github.com/imgeorgiev/DiffRL.git/#subdirectory=dflex
      - dm-control==1.0.8
      - mujoco==2.3.1
      - mujoco-py==2.1.2.14

      # start of s4 packages @todo: clean them up
      - numpy
      - scipy
      # - pandas
      - scikit-learn
      - matplotlib
      - tqdm
      - rich
      - torchtext
      - lit # Getting installation errors with torch 2.0 if this isn't installed
      # torchvision
      - pytorch-lightning==2.0.4
      - hydra-core
      - omegaconf
      # wandb
      - einops
      - cmake # For pykeops support
      # pykeops # Seems to cause various issues; leaving uninstalled by default
      - transformers # For some schedulers

      # Model specific packges
      # pytorch-fast-transformers # for Performer

      # Dataset specific packages
      - datasets # LRA
      - sktime # BIDMC
      - scikit-learn # Impedance
      - numba # Impedance
      - gluonts # Monash
      - timm==0.5.4 # ImageNet