name: forl
channels:
  - pytorch
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.8 # TODO try upgrading
  - pytorch-cuda=11.8
  - pytorch
  - cuda=11.8
  - cuda-toolkit=11.8
  - pandas
  - matplotlib
  - seaborn
  - notebook
  - pip
  - pip:
      - git+https://github.com/mmatl/urdfpy.git # hasn't released a new version in a while
      - usd-core
      - hydra-core
      - wandb
      - black
      - tensorboardX
      - rl_games
