name: forl
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - pandas
  - matplotlib
  - seaborn
  - notebook
  - pip
  - pip:
      - hydra-core
      - wandb
      - black
      - tensorboardX
      - rl_games # used as a baseline for comparison. Not required!
      # dflex simulator is used for examples. It is not required for the library.
      - git+https://github.com/imgeorgiev/DiffRL.git/#subdirectory=dflex

