_target_: forl.algorithms.fowm.FOWM
_recursive_: False
actor_config:
  _target_: forl.models.actor.ActorStochasticMLP
  units: ${resolve_child:[400, 200, 100],${env.shac.actor_mlp},units}
  activation_class: nn.Mish
  init_gain: 1.0
  init_logstd: -1.0
critic_config:
  _target_: forl.models.critic.CriticMLP
  units: ${resolve_child:[400, 200],${env.shac.critic_mlp},units}
  activation_class: nn.Mish
model_config:
  _target_: forl.models.mlp.MLP
  units: [400, 200]
reward_config:
  _target_: forl.models.mlp.MLP
  units: [400, 200]
terminate_config:
  _target_: forl.models.mlp.MLP
  units: [400, 200]
  activation_cfg_last:
    _target_: torch.nn.Sigmoid
num_critics: 3
actor_lr: ${resolve_child:2e-3,${env.shac},actor_lr}
critic_lr: ${resolve_child:5e-4,${env.shac},critic_lr}
model_lr: 2e-3
lr_schedule: linear
obs_rms: True
rew_rms: True
ret_rms: False
critic_iterations: 16
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:2000,${env.shac},max_epochs}
horizon: 16
actor_grad_norm: 1.0 # Can also be none
critic_grad_norm: 100.0 # Can also be none
wm_batch_size: 5
wm_iterations: 4
wm_grad_norm: 20.0
save_interval: ${resolve_child:400,${env.shac},save_interval}
device: ${general.device}
