_target_: forl.algorithms.fowm4.FOWM
_recursive_: False
actor_config:
  _target_: forl.models.actor.ActorStochasticMLP
  units: ${resolve_child:[400, 200, 100],${env.shac.actor_mlp},units}
  activation_class: nn.Mish
  init_gain: 1.0
  init_logstd: -1.0
critic_config:
  _target_: forl.models.critic.CriticMLP
  units: ${resolve_child:[400, 200],${env.shac.critic_mlp},units}
  activation_class: nn.Mish
world_model_config:
  _target_: forl.models.world_model.WorldModel
  units: [512, 512]
  encoder_units: [256]
  # last_layer: linear # or spectralnormlinear
  # last_layer_kwargs: {}
  # last_layer: normedlinear
  # last_layer_kwargs:
  #   act:
  #     _target_: forl.models.mlp.SimNorm
  #     simnorm_dim: 8
  # last_layer: spectralnormlinear
  # last_layer_kwargs:
  #   layer_norm: True
  #   act:
  #     _target_: forl.models.mlp.SimNorm
  #     simnorm_dim: 8
  encoder:
    last_layer: normedlinear
    last_layer_kwargs:
      act:
        _target_: forl.models.mlp.SimNorm
        simnorm_dim: 8
  dynamics:
    last_layer: normedlinear
    last_layer_kwargs:
      act:
        _target_: forl.models.mlp.SimNorm
        simnorm_dim: 8
  reward:
    last_layer: linear # or spectralnormlinear
    last_layer_kwargs: {}
num_critics: 3
latent_dim: 512
actor_lr: ${resolve_child:2e-3,${env.shac},actor_lr}
critic_lr: ${resolve_child:5e-4,${env.shac},critic_lr}
model_lr: 3e-4
lr_schedule: linear
obs_rms: False
rew_rms: True
ret_rms: False
critic_iterations: 8 # 16 was the tune for H=32
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:2000,${env.shac},max_epochs}
horizon: 16
actor_grad_norm: 1.0 # Can also be none
critic_grad_norm: 100.0 # Can also be none
wm_batch_size: 256
wm_iterations: 4 # 1 is bad but too much is unnecessary
wm_grad_norm: 20.0
wm_buffer_size: 10_000_000
with_terminate: False # doesn't work right now
save_interval: ${resolve_child:400,${env.shac},save_interval}
device: ${general.device}
ent_coef: 0.0 # doesn't help
detach: False
