config:
  _target_: dflex.envs.AntEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 128
  stochastic_init: True
  no_grad: False
  episode_length: 1000
  MM_caching_frequency: 16
  early_termination: True

shac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 2000
  save_interval: 400
  target_critic_alpha: 0.99
  actor_mlp:
    units: [400, 200, 100]
  critic_mlp:
    units: [400, 200, 100]
